import { ArrowRight, BadgeCheck, HeartPulse, MessageCircle, ShieldCheck, WalletCards } from 'lucide-react'
import { motion } from 'framer-motion'

const features = [{ icon: MessageCircle, title: 'Dual Accessibility.', text: 'Workers with smartphones can download our rich app, while keypad phone users get the exact same matching power via Toll-Free IVR and SMS. Nobody is left behind.', accent: 'orange' }, { icon: BadgeCheck, title: 'Unique Digital Identity.', text: 'Every worker gets a verifiable ID card generated on our platform for safe, on-site verification.', accent: 'blue' }, { icon: WalletCards, title: 'Verified payments', text: 'Jobs stay open until the worker uploads a payment photo or screenshot.', accent: 'green' }, { icon: BadgeCheck, title: 'Portable trust score', text: 'Ratings belong to the worker and carry over wherever their work takes them.', accent: 'yellow' }, { icon: HeartPulse, title: 'Instant SOS', text: 'A one-tap safety button freezes an employer account when a worker needs help.', accent: 'orange' }, { icon: ShieldCheck, title: 'Digital proof of income', text: 'Automated ledgers help workers finally apply for loans and benefits.', accent: 'blue' }]
const comparisons = [{ label: 'Discovery', old: '2–6 hrs unpaid wait time at a chowk', next: '< 2 min AI-driven local match' }, { label: 'Fees', old: '10–20% lost to middlemen', next: '₹0 worker commission' }, { label: 'Trust', old: 'Unknown workers with no history', next: 'Verified portable trust scores' }, { label: 'Safety', old: 'No backup or tracking', next: 'Real-time SOS and location mapping' }]

function ComparisonCard({ title, tone, side }) {
  return <motion.article className={`comparison-card ${tone}`} whileHover={{ y: -12, scale: 1.02 }} transition={{ type: 'spring', stiffness: 240, damping: 20 }}><span className="comparison-card-label">{side}</span><h3>{title}</h3><div className="comparison-points">{comparisons.map(({ label, old, next }) => <motion.div className="comparison-point" key={label} whileHover={{ x: side === 'The DanikJeevi way' ? 8 : 0, opacity: side === 'The old way' ? .5 : 1 }}><span>{label}</span><strong>{side === 'The old way' ? old : next}</strong></motion.div>)}</div></motion.article>
}

export default function Features({ isDark }) { return <section className="section features-section" id="how"><div className="container"><motion.div className="section-heading narrow" initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><span className="eyebrow">The DanikJeevi difference</span><h2 className="text-slate-900 dark:text-white">Work should feel like a <em>choice.</em></h2><p>Simple for a worker on a phone. Powerful for an employer who needs the right people today.</p></motion.div><div className="feature-grid">{features.map(({ icon: Icon, title, text, accent }, i) => <motion.article className={`feature-card ${accent}`} key={title} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .06 }} whileHover={{ y: -8, scale: 1.02 }}><div className="feature-icon"><Icon size={21} /></div><h3 className="text-slate-900 dark:text-white font-bold text-xl mb-2" style={{ color: isDark ? '#ffffff' : '#0f172a' }}>{title}</h3><p className="text-slate-600 dark:text-slate-300 text-sm leading-relaxed" style={{ color: isDark ? '#e2e8f0' : '#475569' }}>{text}</p><a className="text-blue-600 dark:text-blue-400 font-semibold text-sm hover:underline inline-flex items-center gap-1 mt-4" href="#top" aria-label={`Explore ${title}`}>Explore <ArrowRight size={15} /></a></motion.article>)}</div><div className="comparison-cards"><ComparisonCard title="The old way" side="The old way" tone="comparison-old-card" /><ComparisonCard title="A fairer daily rhythm" side="The DanikJeevi way" tone="comparison-new-card" /></div></div></section> }