import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRight, BriefcaseBusiness, HardHat, Moon, ShieldCheck, Sun, X } from 'lucide-react'
import { useState } from 'react'

export default function Navbar({ dark, setDark }) {
  const [isLoginOpen, setIsLoginOpen] = useState(false)
  const [loginTab, setLoginTab] = useState('customer')

  return <header className="nav-wrap"><nav className="nav container fixed top-0 inset-x-0 z-50 h-16 bg-background/80 backdrop-blur-md border-b border-border/40" aria-label="Primary navigation"><a className="brand" href="#top" aria-label="DanikJeevi home"><span className="brand-mark">d<span>j</span></span><span className="brand-name text-slate-900 dark:text-white font-bold text-xl">DanikJeevi</span></a><div className="nav-links"><a href="#problem">The problem</a><a href="#how">How it works</a><a href="#impact">Impact</a></div><div className="nav-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun size={17} /> : <Moon size={17} />}</button><button className="nav-cta" onClick={() => setIsLoginOpen(true)}>Login</button></div></nav><AnimatePresence>{isLoginOpen && <motion.div className="login-overlay bg-slate-900/60 backdrop-blur-sm" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setIsLoginOpen(false)}><motion.div className="login-modal bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white rounded-2xl p-6 shadow-2xl" initial={{ opacity: 0, y: 30, scale: .94 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 20, scale: .95 }} transition={{ type: 'spring', stiffness: 320, damping: 25 }} onClick={event => event.stopPropagation()}><button className="modal-close" onClick={() => setIsLoginOpen(false)} aria-label="Close login"><X size={18} /></button><span className="eyebrow">Welcome to the network</span><h3>Login to DanikJeevi</h3><div className="login-tabs bg-slate-200/70 dark:bg-slate-800 p-1 rounded-xl flex gap-1 w-full my-4 border border-slate-300/50 dark:border-slate-700/50" role="tablist"><button className={loginTab === 'customer' ? 'active login-tab-active' : 'login-tab-inactive'} onClick={() => setLoginTab('customer')} role="tab" aria-selected={loginTab === 'customer'}><BriefcaseBusiness size={16} /> Customer Login</button><button className={loginTab === 'worker' ? 'active login-tab-active' : 'login-tab-inactive'} onClick={() => setLoginTab('worker')} role="tab" aria-selected={loginTab === 'worker'}><HardHat size={16} /> Worker Login</button></div><AnimatePresence mode="wait"><motion.div className="login-form" key={loginTab} initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }} transition={{ duration: .2 }}>{loginTab === 'customer' ? <><label>Phone or email<input placeholder="you@example.com" /></label><small className="form-note">We will send a secure one-time password.</small></> : <><label>e-Shram UAN<input placeholder="Enter your 12-digit UAN" /></label><small className="form-note"><ShieldCheck size={14} /> This generates your unique DanikJeevi ID for site verification.</small></>}<button className="form-submit">Continue <ArrowRight size={16} /></button></motion.div></AnimatePresence></motion.div></motion.div>}</AnimatePresence></header>
}